name: Run Nepse Script

on:
  schedule:
    - cron: "0 9 * * *"   # Every day at 9:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install --upgrade nepse-scraper pandas requests

      - name: Run Nepse Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ✅ inject secret
        run: python nepse_ck.py
