name: Run Nepse Script

on:
  schedule:
    - cron: "30 9 * * *"   # Every day at 9:00 UTC
  workflow_dispatch:       # Allow manual run
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    # 👇 Needed so the GITHUB_TOKEN can write to your repo
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install --upgrade nepse-scraper pandas requests

      - name: Run Nepse Script
        env:
          # 👇 Pass GitHub Actions token to your script
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python delfile.py





